### ISSUE TITLE
[Dashboard] Portfolio Breakdown / Pie Chart

### ISSUE THREAD

**Issue by dated** [PayvoHQ/wallet#567]
The redesigned Dashboard will feature a portfolio breakdown and pie chart, designs can be found in Figma, questions will be answered on Slack.

## Portfolio Breakdown

![image](https://user-images.githubusercontent.com/6547002/141144588-2331b003-a67e-4356-9074-2a099ddcc3c0.png)
![image](https://user-images.githubusercontent.com/6547002/141144752-ae252c98-a1b7-45da-a8f5-d84eceae75ef.png)

- `Your Balance` is the total balance of all wallets belonging to Public Networks. The number of decimals is dictated by the configured currency setting.
- `Assets` is the number of all Public Networks the user has added wallets of. Development and test networks are not counted.
- `Wallets` is the number of all wallets belonging to Public Networks added to the Payvo Wallet. Wallets belonging to development or test networks are not counted.
- `More Details` will open the pie-chart modal (outlined below). If there are no wallets, only wallets belonging to developments and test networks, or the total balance is zero, then this button is grayed out and disabled.

### Tasks

- [ ] https://github.com/PayvoHQ/wallet/issues/568
- [ ] https://github.com/PayvoHQ/wallet/issues/569

## Pie-Chart Modal

![image](https://user-images.githubusercontent.com/6547002/141133773-a8db931b-83a6-4d11-a56e-aece11c0b837.png)
![image](https://user-images.githubusercontent.com/6547002/141133797-dfdcc1a9-a6e3-4c76-8b96-7c3427d35fbd.png)

#### Chart

- The total currency value of Public Network assets in the currency configured by the user is displayed in the center.
  - the decimals have a smaller font size
  - if the value surpasses 1 million the amount is rounded down and displayed in millions, with a tooltip showing the exact amount on hover
- Upon hovering a segment a tooltip showing the asset name and percentage is displayed.
- The five assets with the biggest percentage are assigned each their own color and segment, the remaining assets are grouped together as `Other`.
  - if there is only one "other" asset, its name is used instead.

#### Table

- The table has the following columns: Asset, Balance, Currency, Percentage (%)
- The five assets with the biggest percentage are assigned each their own color, the remaining assets are gray.
- 
### Tasks

- [ ] https://github.com/PayvoHQ/wallet/issues/570
- [ ] https://github.com/PayvoHQ/wallet/issues/571

#### Colors used for the assets ordered by percentage (descending)

1. `green-600`
2. `yellow-600`
3. `blue-600`
4. `red-400`
5. `purple-400`
6. `gray-400`

Special case: When there are no assets with a currency value then the line of the porfolio breakdown should use `gray-300`.

#### Example configurations for multiple assets

- 1 asset (1 color - green)
- 2 assets (2 colors - green + orange)
- 3 assets (3 colors - green + orange + blue)
- 4 assets (4 colors - green + orange + blue + red)
- 5 assets (5 colors - green + orange + blue + red + purple)
- 6 assets (6 colors - green + orange + blue + red + purple + gray)
- 7+ assets (6 colors - green + orange + blue + red + purple + gray where gray takes space of all other coins that have low percentage and are grouped as `Other`)
